name: fps_jank_flash_widget
description: A flutter widget that flashes when flutter fails to render a frame in a certain timeframe
version: 1.1.0+3
repository: https://github.com/lesnitsky/fps_jank_flash_widget

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
